# Site settings
title: Glenn's Jekyll Site
email: glenn.zucman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks 4 visiting my site. <a href="http://jekyll.zucman.com/contact">Find me online!</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jekyll.zucman.com" # the base hostname & protocol for your site
twitter_username: glenn_irs
github_username:  glenn-irs

# Build settings
markdown: kramdown
theme: minima
disqus:
  shortname: art490
    
